apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T19:15:00Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5700"
  uid: 3c2be23d-4b4f-49ea-9527-cc59f8d8b614
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.127.210
  clusterIPs:
  - 10.96.127.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31408
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
